/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
export default {
    darkMode: "class",
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./node_modules/flowbite/**/*.js",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: "var(--primary-color)", // Usamos la variable CSS como valor por defecto
                    50: "var(--primary-color-50)",
                    100: "var(--primary-color-100)",
                    200: "var(--primary-color-200)",
                    300: "var(--primary-color-300)",
                    400: "var(--primary-color-400)",
                    500: "var(--primary-color-500)",
                    600: "var(--primary-color-600)",
                    700: "var(--primary-color-700)",
                    800: "var(--primary-color-800)",
                    900: "var(--primary-color-900)",
                    950: "var(--primary-color-950)",
                },
                "pink-store": "var(--pink)",
                "blue-store": "var(--blue)",
                "brown-store": "var(--brown)",
                "green-store": "var(--green)",
                "gray-store": "var(--gray)",
                "peach-store": "var(--peach)",
                "light-pink": "var(--light-pink)",
                "light-gray": "var(--light-gray)",
                "light-blue": "var(--light-blue)",
                "light-blue-2": "var(--light-blue-2)",
                "dark-pink": "var(--dark-pink)",
                "dark-blue": "var(--dark-blue)",
                "blue-selected": "var(--blue-selected)",
                "pink-selected": "var(--pink-selected)",
                "green-selected": "var(--green-selected)",
                "dark-blue-selected": "var(--dark-blue-selected)",
            },
            opacity: {
                10: "0.1",
                20: "0.2",
                30: "0.3",
                40: "0.4",
                50: "0.5",
                60: "0.6",
                70: "0.7",
                80: "0.8",
                90: "0.9",
            },
            fontFamily: {
                "pluto-m": ["pluto-m", "sans-serif"],
                "pluto-r": ["pluto-r", "sans-serif"],
                "din-b": ["din-b", "sans-serif"],
                "din-r": ["din-r", "sans-serif"],
                "din-i": ["din-i", "sans-serif"],
                "dinc-b": ["dinc-b", "sans-serif"],
                "dinc-r": ["dinc-r", "sans-serif"],
                "dine-b": ["dine-b", "sans-serif"],
                "dine-i": ["dine-i", "sans-serif"],
                "dine-r": ["dine-r", "sans-serif"],
                poppins: ["Poppins", "sans-serif"],
            },
        },
    },
    plugins: [
        require("flowbite/plugin"),
        require("tailwindcss-animated"),
        require("tailwindcss-textshadow"),
    ],
};
