import "./bootstrap";
import "./jquery";
import "flowbite";
import "./loginAdmin";
import "./customSelect";
import "./script";
import "./categorie";
import "./brand";
import "./product";
import "./modal-image";
import "./flash-offers";
import "./popup";
import "./user";
import "./faq";
import "./swiper";
import "./product-view";
import "./cart";
import "./drawer";
import "./sales-strategies";
import "./navbar";
import "./loader";
import "./store";
import "./checkout";
import "./policies";
import "./general-settings";
import "./calendar";
import "./chart";
import "./dashboard";
import "./settings";
import "./customer";
import "./order";
import "./reviews";
import "./ticket";
import "./register";
import "./filters-store";
import { initSwiper } from "./swiper";

initSwiper();
